### ISSUE TITLE
director role: "Creating directories for templates and images" the directories are created under "/root" user with default values.

### ISSUE THREAD

**Issue by shwetha-h-p** [oasis-roles/ansible_collection_osp#2]
Referring to the file: https://github.com/oasis-roles/ansible_collection_osp/blob/master/roles/director/tasks/main.yml  line number 9 - 20.

The  templates, images directory are to be created under "/home/stack".

https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html/director_installation_and_usage/installing-the-undercloud#creating-directories-for-templates-and-images

In the role, the defaults are:

osp_director_become: true
osp_director_become_user: root

Hence , the directories are created under "/root"

TASK [director : 4.2 Creating directories for templates and images] ***********************************************************************************************************************************************
ok: [10.0.101.242] => (item=~/images) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "~/images", "mode": "0755", "owner": "root", "path": "/root/images", "secontext": "unconfined_u:object_r:admin_home_t:s0", "size": 6, "state": "directory", "uid": 0}
ok: [10.0.101.242] => (item=~/templates) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "~/templates", "mode": "0755", "owner": "root", "path": "/root/templates", "secontext": "unconfined_u:object_r:admin_home_t:s0", "size": 6, "state": "directory", "uid": 0}

**Comment by greg-hellings** [comment]
I plan to

* Make this configurable by the caller
* Change the default to `{{ ansible_user_dir }}` which will be ~/ as resolved by the login user rather than the `become_user`.

**Comment by greg-hellings** [comment]
These are now created under `osp_director_stage` (configurable by user, defaults to `/home/stack`) and user is hard-coded as "stack"
