### ISSUE TITLE
template role: The files copied has the owner 'root' even when the "osp_templates_become_user" is "non_root_user" . For ex: osp_templates_become_user: stack

### ISSUE THREAD

**Issue by shwetha-h-p** [oasis-roles/ansible_collection_osp#4]
Playbook:
====================
# Copy templates before install the director
- name: Copy templates
  hosts: undercloud
  roles:
    - role: oasis_roles.osp.templates
      osp_templates_input_dir: "{{ lookup('env','WORKSPACE') }}/ansible/playbooks/files/cloud/undercloud/"
      osp_templates_output_dir: "/home/stack/cloud/"
      osp_templates_copy_only: true
      osp_templates_become: true
      osp_templates_become_user: stack

The playbook executed successfully and copied the files to the undercloud node's "/home/stack/cloud"

The playbook created the dir "/home/stack/cloud" (this directory didn't exists before). The owner, group of this directory is properly set. But the copied files have the "root" as owner. Following the out of the "ls" command on the "/home/stack" directory.

[stack@director-osp13 ~]$ ls -lart
total 16
-rw-r--r--. 1 stack stack 231 Mar 12  2019 .bashrc
-rw-r--r--. 1 stack stack 193 Mar 12  2019 .bash_profile
-rw-r--r--. 1 stack stack  18 Mar 12  2019 .bash_logout
drwxr-xr-x. 4 root  root   37 May 28 10:13 ..
drwx------. 3 stack stack  17 May 28 13:22 .ansible
drwxr-----. 3 stack stack  19 May 29 09:21 .pki
-rw-------. 1 stack stack 902 Jun  1 08:43 .bash_history
drwx------. 5 stack stack 124 Jun  1 08:47 .
**drwxr-xr-x. 2 stack stack  51 Jun  1 08:47 cloud**

[stack@director-osp13 ~]$ ls -lart cloud/
total 20
drwx------. 5 stack stack   124 Jun  1 08:47 ..
**-rw-r--r--. 1 root  root  14216 Jun  1 08:47 undercloud.conf
-rw-r--r--. 1 root  root    102 Jun  1 08:47 hieradata.yaml**
drwxr-xr-x. 2 stack stack    51 Jun  1 08:47

**Comment by greg-hellings** [comment]
This is working properly, as expected. Do not use `become` to set the owner of the resulting files. Use the `osp_templates_owner` value. I've added a test that confirms everything is working properly in 9f0c1e7.

**Comment by shwetha-h-p** [comment]
I used 'osp_templates_become_user' and 'osp_templates_become' because the ansible_user is "cloud-user"  and not "stack" user.  The cloud-user doesn't have permissions to  create dirs/files as "stack" user. 

**I tried without setting** the osp_templates_become and osp_template_become_user:

# Copy templates before install the director
- name: Copy templates
  hosts: undercloud
  roles:
    - role: oasis_roles.osp.templates
  vars:
    osp_templates_input_dir: "{{ lookup('env','WORKSPACE') }}/scenario/css_openstack/ansible/playbooks/files/cloud/undercloud/"
    osp_templates_output_dir: "{{ osp_director_templates }}"
    osp_templates_copy_only: true

PLAY [Copy templates] *********************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [10.0.101.242]

**TASK [templates : make sure /home/stack/cloud/ exists]** ************************************************************************************************************************************************************
**fatal: [10.0.101.242]: FAILED! => {"changed": false, "msg": "There was an issue creating /home/stack/cloud as requested: [Errno 13] Permission denied: '/home/stack/cloud'", "path": "/home/stack/cloud/"}**

PLAY RECAP ********************************************************************************************************************************************************************************************************
10.0.101.242               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

When ran without setting the osp_templates_become and osp_templates_become_user, the playbook fails as the ansible_user is "cloud-user". Hence setting one of the following doesn't fail the playbook. 

1)
# Copy templates before install the director
- name: Copy templates
  hosts: undercloud
  roles:
    - role: oasis_roles.osp.templates
      osp_templates_input_dir: "{{ lookup('env','WORKSPACE') }}/scenario/css_openstack/ansible/playbooks/files/cloud/undercloud/"
      osp_templates_output_dir: "{{ osp_director_templates }}"
      osp_templates_copy_only: true
      **osp_templates_become: true
      osp_templates_become_user: stack**

2)
# Copy templates before install the director
- name: Copy templates
  hosts: undercloud
  roles:
    - role: oasis_roles.osp.templates
      osp_templates_input_dir: "{{ lookup('env','WORKSPACE') }}/scenario/css_openstack/ansible/playbooks/files/cloud/undercloud/"
      osp_templates_output_dir: "{{ osp_director_templates }}"
      osp_templates_copy_only: true
      **osp_templates_become: true**


Now ever after setting the "osp_templates_owner" to stack the files  and directories created doesn't have the owner set as "stack".  The ownership is set only on the top directory but not recursively.

#######################
Playbook executed:
#######################
- name: Copy templates
  hosts: undercloud
  roles:
    - role: oasis_roles.osp.templates
      osp_templates_input_dir: "{{ lookup('env','WORKSPACE') }}/scenario/css_openstack/ansible/playbooks/files/cloud/"
      osp_templates_output_dir: "/home/stack/cloud_new"
      osp_templates_copy_only: true
      osp_templates_owner: stack
      osp_templates_become: true


**drwxr-xr-x.  4 stack root    41 Jun  2 03:30 cloud_new**


[stack@director-osp13 ~]$ ls -lart cloud_new/
total 4
drwx------. 10 stack stack 4096 Jun  2 03:30 ..
**drwxr-xr-x.  2 root  root     6 Jun  2 03:30 overcloud**
drwxr-xr-x.  4 stack root    41 Jun  2 03:30 .
**drwxr-xr-x.  2 root  root    83 Jun  2 03:30 undercloud**

[stack@director-osp13 ~]$ ls -lart cloud_new/overcloud/
total 0
drwxr-xr-x. 4 stack root 41 Jun  2 03:30 ..
drwxr-xr-x. 2 root  root  6 Jun  2 03:30 .

[stack@director-osp13 ~]$ ls -lart cloud_new/undercloud/
total 24
drwxr-xr-x. 4 stack root    41 Jun  2 03:30 ..
**-rw-r--r--. 1 root  root   102 Jun  2 03:30 hieradata.yaml
-rw-r--r--. 1 root  root   510 Jun  2 03:30 undercloud.conf
-rw-r--r--. 1 root  root 14210 Jun  2 03:30 psi-prod-undercloud.conf**
drwxr-xr-x. 2 root  root    83 Jun  2 03:30 .
