### ISSUE TITLE
director role: Failed to source the stackrc file as we are running the task as non "stack" user

### ISSUE THREAD

**Issue by shwetha-h-p** [oasis-roles/ansible_collection_osp#6]
When we are running the playbook, the ansible_user is different (cloud-user as we are deploying it on openstack). In the playbook https://github.com/oasis-roles/ansible_collection_osp/blob/master/roles/director/tasks/main.yml  line number 90 we are sourcing the stackrc file without becoming the stack user. 

TASK [director : Source stackrc] **********************************************************************************************************************************************************************************
fatal: [10.0.102.203]: FAILED! => {"changed": false, "cmd": "set -e\nsource ~/stackrc\nenv\n", "delta": "0:00:00.007390", "end": "2020-06-02 02:59:34.471025", "msg": "non-zero return code", "rc": 1, "start": "2020-06-02 02:59:34.463635", **"stderr": "/bin/sh: line 1: /home/cloud-user/stackrc: No such file or directory", "stderr_lines": ["/bin/sh: line 1: /home/cloud-user/stackrc: No such file or directory"], "stdout": "", "stdout_lines": []}**

PLAY RECAP ********************************************************************************************************************************************************************************************************
10.0.102.203               : ok=10   changed=7    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by greg-hellings** [comment]
Duplicate issue.
