### ISSUE TITLE
template role: The files copied has the owner 'root' even when the osp_templates_owner is set

### ISSUE THREAD

**Issue by shwetha-h-p** [oasis-roles/ansible_collection_osp#7]
Ever after setting the "osp_templates_owner" to stack the files and directories created doesn't have the owner set as "stack". The ownership is set only on the top directory but not recursively.

#######################
Playbook executed:
#######################

name: Copy templates
hosts: undercloud
roles:
role: oasis_roles.osp.templates
osp_templates_input_dir: "{{ lookup('env','WORKSPACE') }}/scenario/css_openstack/ansible/playbooks/files/cloud/"
osp_templates_output_dir: "/home/stack/cloud_new"
osp_templates_copy_only: true
osp_templates_owner: stack
osp_templates_become: true
drwxr-xr-x. 4 stack root 41 Jun 2 03:30 cloud_new

[stack@director-osp13 ~]$ ls -lart cloud_new/
total 4
drwx------. 10 stack stack 4096 Jun 2 03:30 ..
drwxr-xr-x. 2 root root 6 Jun 2 03:30 overcloud
drwxr-xr-x. 4 stack root 41 Jun 2 03:30 .
drwxr-xr-x. 2 root root 83 Jun 2 03:30 undercloud

[stack@director-osp13 ~]$ ls -lart cloud_new/overcloud/
total 0
drwxr-xr-x. 4 stack root 41 Jun 2 03:30 ..
drwxr-xr-x. 2 root root 6 Jun 2 03:30 .

[stack@director-osp13 ~]$ ls -lart cloud_new/undercloud/
total 24
drwxr-xr-x. 4 stack root 41 Jun 2 03:30 ..
-rw-r--r--. 1 root root 102 Jun 2 03:30 hieradata.yaml
-rw-r--r--. 1 root root 510 Jun 2 03:30 undercloud.conf
-rw-r--r--. 1 root root 14210 Jun 2 03:30 psi-prod-undercloud.conf
drwxr-xr-x. 2 root root 83 Jun 2 03:30 .

NOTE: Without setting the "osp_templates_become: true" the playbook fails . This is because the playbook is run on the undercloud node with ansible_user: cloud-user. 

The cloud-user doesn't have permissions to create dirs/files under /home/stack user. 

TASK [templates : make sure /home/stack/cloud_new exists] *********************************************************************************************************************************************************
fatal: [10.0.102.203]: FAILED! => {"changed": false, "msg": "There was an issue creating /home/stack/cloud_new as requested: [Errno 13] Permission denied: '/home/stack/cloud_new'", "path": "/home/stack/cloud_new"}

**Comment by greg-hellings** [comment]
Ah, I see why you're having trouble. You're using copy_only mode. That uses rsync to send the files. Working on a fix for it now.

**Comment by greg-hellings** [comment]
Got this sorted, now.
